language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer update

script: ./vendor/bin/phpunit -c phpunit.xml --coverage-text

after_script:
  - php vendor/bin/coveralls -v