language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - mkdir -p build/www
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script: ./vendor/bin/phpunit -c phpunit.xml --coverage-text

after_script:
  - php vendor/bin/coveralls -v
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml; fi