language: php

php:
  - 5.6
  - 7.0

sudo: false

before_script:
  - mkdir -p build/www
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script: ./vendor/bin/phpunit -c phpunit.xml --coverage-text

after_script:
  - php vendor/bin/coveralls -v
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml